# Site settings
title: Photoshop Scripting Cookbook
email: davide.barranca@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Collection of Scripts for Adobe Photoshop
baseurl: "/Photoshop-Scripting-Cookbook" # the subpath of your site, e.g. /blog/
twitter_username: undavide
github_username:  undavide

# Build settings
markdown: kramdown
pygments: true
github: site.github.repository_url